val efetividadePorPokemon = mapOf(
    "Bulbasaur" to listOf("FIRE", "ICE", "FLYING", "PSYCHIC"),
    "Ivysaur" to listOf("FIRE", "ICE", "FLYING", "PSYCHIC"),
    "Venusaur" to listOf("FIRE", "ICE", "FLYING", "PSYCHIC"),
    "Charmander" to listOf("WATER", "GROUND", "ROCK"),
    "Charmeleon" to listOf("WATER", "GROUND", "ROCK"),
    "Charizard" to listOf("WATER", "GROUND", "ROCK"),
    "Squirtle" to listOf("ELECTRIC", "GRASS"),
    "Wartortle" to listOf("ELECTRIC", "GRASS"),
    "Blastoise" to listOf("ELECTRIC", "GRASS"),
    "Caterpie" to listOf("FIRE", "FLYING", "ROCK"),
    "Metapod" to listOf("FIRE", "FLYING", "ROCK"),
    "Butterfree" to listOf("FIRE", "FLYING", "ROCK"),
    "Weedle" to listOf("FIRE", "FLYING", "ROCK"),
    "Kakuna" to listOf("FIRE", "FLYING", "ROCK"),
    "Beedrill" to listOf("FIRE", "FLYING", "ROCK"),
    "Pidgey" to listOf("ELECTRIC", "ICE", "ROCK"),
    "Pidgeotto" to listOf("ELECTRIC", "ICE", "ROCK"),
    "Pidgeot" to listOf("ELECTRIC", "ICE", "ROCK"),
    "Rattata" to listOf("FIGHTING"),
    "Raticate" to listOf("FIGHTING"),
    "Spearow" to listOf("ELECTRIC", "ICE", "ROCK"),
    "Fearow" to listOf("ELECTRIC", "ICE", "ROCK"),
    "Ekans" to listOf("PSYCHIC", "GROUND"),
    "Arbok" to listOf("PSYCHIC", "GROUND"),
    "Pikachu" to listOf("GROUND"),
    "Raichu" to listOf("GROUND"),
    "Sandshrew" to listOf("WATER", "ICE", "GRASS", "FIGHTING"),
    "Sandslash" to listOf("WATER", "ICE", "GRASS", "FIGHTING"),
    "Nidoran♀" to listOf("PSYCHIC", "GROUND"),
    "Nidorina" to listOf("PSYCHIC", "GROUND"),
    "Nidoqueen" to listOf("PSYCHIC", "GROUND", "ICE", "FIGHTING"),
    "Nidoran♂" to listOf("PSYCHIC", "GROUND"),
    "Nidorino" to listOf("PSYCHIC", "GROUND"),
    "Nidoking" to listOf("PSYCHIC", "GROUND", "ICE", "FIGHTING"),
    "Clefairy" to listOf("STEEL", "POISON", "FIGHTING"),
    "Clefable" to listOf("STEEL", "POISON", "FIGHTING"),
    "Vulpix" to listOf("WATER", "GROUND", "ROCK"),
    "Ninetales" to listOf("WATER", "GROUND", "ROCK"),
    "Jigglypuff" to listOf("STEEL", "POISON", "FIGHTING"),
    "Wigglytuff" to listOf("STEEL", "POISON", "FIGHTING"),
    "Zubat" to listOf("PSYCHIC", "ELECTRIC", "FLYING"),
    "Golbat" to listOf("PSYCHIC", "ELECTRIC", "FLYING"),
    "Oddish" to listOf("FIRE", "ICE", "FLYING", "BUG"),
    "Gloom" to listOf("FIRE", "ICE", "FLYING", "BUG"),
    "Vileplume" to listOf("FIRE", "ICE", "FLYING", "BUG"),
    "Paras" to listOf("FIRE", "ICE", "FLYING", "BUG"),
    "Parasect" to listOf("FIRE", "ICE", "FLYING", "BUG"),
    "Venonat" to listOf("PSYCHIC", "FIRE", "ICE", "FLYING", "BUG"),
    "Venomoth" to listOf("PSYCHIC", "FIRE", "ICE", "FLYING", "BUG"),
    "Diglett" to listOf("WATER", "ICE", "FLYING", "FIGHTING"),
    "Dugtrio" to listOf("WATER", "ICE", "FLYING", "FIGHTING"),
    "Meowth" to listOf("FIGHTING"),
    "Persian" to listOf("FIGHTING"),
    "Psyduck" to listOf("ELECTRIC", "GRASS"),
    "Golduck" to listOf("ELECTRIC", "GRASS"),
    "Mankey" to listOf("PSYCHIC", "FIGHTING", "FIRE"),
    "Primeape" to listOf("PSYCHIC", "FIGHTING", "FIRE"),
    "Growlithe" to listOf("WATER", "GROUND", "ROCK"),
    "Arcanine" to listOf("WATER", "GROUND", "ROCK"),
    "Poliwag" to listOf("ELECTRIC", "GRASS"),
    "Poliwhirl" to listOf("ELECTRIC", "GRASS"),
    "Poliwrath" to listOf("ELECTRIC", "GRASS", "PSYCHIC"),
    "Abra" to listOf("BUG", "DARK", "GHOST"),
    "Kadabra" to listOf("BUG", "DARK", "GHOST"),
    "Alakazam" to listOf("BUG", "DARK", "GHOST"),
    "Machop" to listOf("PSYCHIC", "FLYING", "FIGHTING"),
    "Machoke" to listOf("PSYCHIC", "FLYING", "FIGHTING"),
    "Machamp" to listOf("PSYCHIC", "FLYING", "FIGHTING"),
    "Bellsprout" to listOf("FIRE", "ICE", "FLYING", "BUG"),
    "Weepinbell" to listOf("FIRE", "ICE", "FLYING", "BUG"),
    "Victreebel" to listOf("FIRE", "ICE", "FLYING", "BUG"),
    "Tentacool" to listOf("PSYCHIC", "GROUND", "ELECTRIC"),
    "Tentacruel" to listOf("PSYCHIC", "GROUND", "ELECTRIC"),
    "Geodude" to listOf("WATER", "GRASS", "ICE", "GROUND", "FIGHTING"),
    "Graveler" to listOf("WATER", "GRASS", "ICE", "GROUND", "FIGHTING"),
    "Golem" to listOf("WATER", "GRASS", "ICE", "GROUND", "FIGHTING"),
    "Ponyta" to listOf("WATER", "GROUND", "ROCK"),
    "Rapidash" to listOf("WATER", "GROUND", "ROCK"),
    "Magnemite" to listOf("GROUND", "FIRE"),
    "Magneton" to listOf("GROUND", "FIRE"),
    "Farfetch'd" to listOf("FIGHTING", "BUG"),
    "Doduo" to listOf("ELECTRIC", "ICE", "ROCK"),
    "Dodrio" to listOf("ELECTRIC", "ICE", "ROCK"),
    "Seel" to listOf("ELECTRIC", "GRASS", "FIGHTING"),
    "Dewgong" to listOf("ELECTRIC", "GRASS", "FIGHTING"),
    "Grimer" to listOf("PSYCHIC", "GROUND"),
    "Muk" to listOf("PSYCHIC", "GROUND"),
    "Shellder" to listOf("ELECTRIC", "GRASS", "FIGHTING"),
    "Cloyster" to listOf("ELECTRIC", "GRASS", "FIGHTING"),
    "Gastly" to listOf("GROUND", "PSYCHIC", "DARK"),
    "Haunter" to listOf("GROUND", "PSYCHIC", "DARK"),
    "Gengar" to listOf("GROUND", "PSYCHIC", "DARK"),
    "Onix" to listOf("WATER", "GRASS", "ICE", "FIRE"),
    "Drowzee" to listOf("BUG", "DARK", "GHOST"),
    "Hypno" to listOf("BUG", "DARK", "GHOST"),
    "Krabby" to listOf("ELECTRIC", "GRASS"),
    "Kingler" to listOf("ELECTRIC", "GRASS"),
    "Exeggcute" to listOf("FIRE", "ICE", "FLYING", "BUG"),
    "Exeggutor" to listOf("FIRE", "ICE", "FLYING", "BUG"),
    "Cubone" to listOf("WATER", "GRASS", "ICE", "FIGHTING"),
    "Marowak" to listOf("WATER", "GRASS", "ICE", "FIGHTING"),
    "Lickitung" to listOf("FIGHTING"),
    "Koffing" to listOf("PSYCHIC", "GROUND"),
    "Weezing" to listOf("PSYCHIC", "GROUND"),
    "Rhyhorn" to listOf("WATER", "GRASS", "ICE", "GROUND", "FIGHTING"),
    "Rhydon" to listOf("WATER", "GRASS", "ICE", "GROUND", "FIGHTING"),
    "Chansey" to listOf("FIGHTING"),
    "Tangela" to listOf("FIRE", "ICE", "FLYING", "BUG"),
    "Kangaskhan" to listOf("FIGHTING"),
    "Horsea" to listOf("ELECTRIC", "GRASS"),
    "Seadra" to listOf("ELECTRIC", "GRASS"),
    "Goldeen" to listOf("ELECTRIC", "GRASS"),
    "Seaking" to listOf("ELECTRIC", "GRASS"),
    "Staryu" to listOf("ELECTRIC", "GRASS"),
    "Starmie" to listOf("ELECTRIC", "GRASS"),
    "Mr. Mime" to listOf("BUG", "DARK", "GHOST"),
    "Scyther" to listOf("FIRE", "ELECTRIC", "ICE", "ROCK"),
    "Jynx" to listOf("FIRE", "BUG", "STEEL", "ROCK"),
    "Electrode" to listOf("GROUND", "FIRE"),
    "Exeggutor" to listOf("FIRE", "ICE", "FLYING", "BUG"),
    "Omanyte" to listOf("ELECTRIC", "GRASS", "GROUND", "ROCK"),
    "Omastar" to listOf("ELECTRIC", "GRASS", "GROUND", "ROCK"),
    "Kabuto" to listOf("ELECTRIC", "GRASS", "GROUND", "ROCK"),
    "Kabutops" to listOf("ELECTRIC", "GRASS", "GROUND", "ROCK"),
    "Articuno" to listOf("FIRE", "ELECTRIC", "ROCK"),
    "Zapdos" to listOf("GROUND", "ICE"),
    "Moltres" to listOf("WATER", "ELECTRIC", "ROCK"),
    "Mewtwo" to listOf("BUG", "DARK", "GHOST"),
    "Mew" to listOf("BUG", "DARK", "GHOST")
)
