val pokemon = listOf(
    "Bulbasaur" to listOf("FIRE", "ICE", "FLYING", "PSYCHIC"),
    "Ivysaur" to listOf("FIRE", "ICE", "FLYING", "PSYCHIC"),
    "Venusaur" to listOf("FIRE", "ICE", "FLYING", "PSYCHIC"),
    "Charmander" to listOf("WATER", "ROCK", "GROUND"),
    "Charmeleon" to listOf("WATER", "ROCK", "GROUND"),
    "Charizard" to listOf("WATER", "ROCK", "ELECTRIC"),
    "Squirtle" to listOf("ELECTRIC", "GRASS"),
    "Wartortle" to listOf("ELECTRIC", "GRASS"),
    "Blastoise" to listOf("ELECTRIC", "GRASS"),
    "Caterpie" to listOf("FIRE", "FLYING", "ROCK"),
    "Metapod" to listOf("FIRE", "FLYING", "ROCK"),
    "Butterfree" to listOf("FIRE", "FLYING", "ROCK", "ELECTRIC"),
    "Weedle" to listOf("FIRE", "FLYING", "ROCK", "PSYCHIC"),
    "Kakuna" to listOf("FIRE", "FLYING", "ROCK", "PSYCHIC"),
    "Beedrill" to listOf("FIRE", "FLYING", "ROCK", "PSYCHIC"),
    "Pidgey" to listOf("ELECTRIC", "ROCK", "ICE"),
    "Pidgeotto" to listOf("ELECTRIC", "ROCK", "ICE"),
    "Pidgeot" to listOf("ELECTRIC", "ROCK", "ICE"),
    "Rattata" to listOf("FIGHTING"),
    "Raticate" to listOf("FIGHTING"),
    "Spearow" to listOf("ELECTRIC", "ROCK", "ICE"),
    "Fearow" to listOf("ELECTRIC", "ROCK", "ICE"),
    "Ekans" to listOf("GROUND", "PSYCHIC"),
    "Arbok" to listOf("GROUND", "PSYCHIC"),
    "Pikachu" to listOf("GROUND"),
    "Raichu" to listOf("GROUND"),
    "Sandshrew" to listOf("WATER", "ICE", "GRASS"),
    "Sandslash" to listOf("WATER", "ICE", "GRASS"),
    "Nidoran♀" to listOf("GROUND", "PSYCHIC"),
    "Nidorina" to listOf("GROUND", "PSYCHIC"),
    "Nidoqueen" to listOf("WATER", "ICE", "PSYCHIC"),
    "Nidoran♂" to listOf("GROUND", "PSYCHIC"),
    "Nidorino" to listOf("GROUND", "PSYCHIC"),
    "Nidoking" to listOf("WATER", "ICE", "PSYCHIC"),
    "Clefairy" to listOf("STEEL", "POISON"),
    "Clefable" to listOf("STEEL", "POISON"),
    "Vulpix" to listOf("WATER", "ROCK", "GROUND"),
    "Ninetales" to listOf("WATER", "ROCK", "GROUND"),
    "Jigglypuff" to listOf("STEEL", "POISON", "FIGHTING"),
    "Wigglytuff" to listOf("STEEL", "POISON", "FIGHTING"),
    "Zubat" to listOf("ELECTRIC", "ICE", "ROCK", "PSYCHIC"),
    "Golbat" to listOf("ELECTRIC", "ICE", "ROCK", "PSYCHIC"),
    "Oddish" to listOf("FIRE", "ICE", "FLYING", "PSYCHIC"),
    "Gloom" to listOf("FIRE", "ICE", "FLYING", "PSYCHIC"),
    "Vileplume" to listOf("FIRE", "ICE", "FLYING", "PSYCHIC"),
    "Paras" to listOf("FIRE", "FLYING", "ROCK", "ICE"),
    "Parasect" to listOf("FIRE", "FLYING", "ROCK", "ICE"),
    "Venonat" to listOf("FIRE", "FLYING", "ROCK", "PSYCHIC"),
    "Venomoth" to listOf("FIRE", "FLYING", "ROCK", "PSYCHIC"),
    "Diglett" to listOf("WATER", "ICE", "GRASS"),
    "Dugtrio" to listOf("WATER", "ICE", "FLYING", "FIGHTING"),
    "Meowth" to listOf("FIGHTING"),
    "Persian" to listOf("FIGHTING"),
    "Psyduck" to listOf("ELECTRIC", "GRASS"),
    "Golduck" to listOf("ELECTRIC", "GRASS"),
    "Mankey" to listOf("PSYCHIC", "FLYING"),
    "Primeape" to listOf("PSYCHIC", "FLYING"),
    "Growlithe" to listOf("WATER", "ROCK", "GROUND"),
    "Arcanine" to listOf("WATER", "ROCK", "GROUND"),
    "Poliwag" to listOf("ELECTRIC", "GRASS"),
    "Poliwhirl" to listOf("ELECTRIC", "GRASS"),
    "Poliwrath" to listOf("ELECTRIC", "GRASS", "FLYING"),
    "Abra" to listOf("BUG", "GHOST", "DARK"),
    "Kadabra" to listOf("BUG", "GHOST", "DARK"),
    "Alakazam" to listOf("BUG", "GHOST", "DARK"),
    "Machop" to listOf("PSYCHIC", "FLYING"),
    "Machoke" to listOf("PSYCHIC", "FLYING"),
    "Machamp" to listOf("PSYCHIC", "FLYING"),
    "Bellsprout" to listOf("FIRE", "ICE", "FLYING", "PSYCHIC"),
    "Weepinbell" to listOf("FIRE", "ICE", "FLYING", "PSYCHIC"),
    "Victreebel" to listOf("FIRE", "ICE", "FLYING", "PSYCHIC"),
    "Tentacool" to listOf("ELECTRIC", "PSYCHIC"),
    "Tentacruel" to listOf("ELECTRIC", "PSYCHIC"),
    "Geodude" to listOf("WATER", "GRASS", "ICE", "STEEL", "GROUND"),
    "Graveler" to listOf("WATER", "GRASS", "ICE", "STEEL", "GROUND"),
    "Golem" to listOf("WATER", "GRASS", "ICE", "STEEL", "GROUND"),
    "Ponyta" to listOf("WATER", "ROCK", "GROUND"),
    "Rapidash" to listOf("WATER", "ROCK", "GROUND"),
    "Slowpoke" to listOf("ELECTRIC", "GRASS"),
    "Slowbro" to listOf("ELECTRIC", "GRASS"),
    "Magnemite" to listOf("FIRE", "GROUND", "FIGHTING"),
    "Magneton" to listOf("FIRE", "GROUND", "FIGHTING"),
    "Farfetch’d" to listOf("FIGHTING", "ROCK"),
    "Doduo" to listOf("ELECTRIC", "ROCK", "ICE"),
    "Dodrio" to listOf("ELECTRIC", "ROCK", "ICE"),
    "Seel" to listOf("ELECTRIC", "GRASS", "FIGHTING"),
    "Dewgong" to listOf("ELECTRIC", "GRASS", "FIGHTING"),
    "Grimer" to listOf("GROUND", "PSYCHIC"),
    "Muk" to listOf("GROUND", "PSYCHIC"),
    "Shellder" to listOf("ELECTRIC", "GRASS"),
    "Cloyster" to listOf("ELECTRIC", "GRASS"),
    "Gastly" to listOf("DARK", "GHOST"),
    "Haunter" to listOf("DARK", "GHOST"),
    "Gengar" to listOf("DARK", "GHOST"),
    "Onix" to listOf("WATER", "GRASS", "FIGHTING", "GROUND", "STEEL"),
    "Drowzee" to listOf("BUG", "GHOST"),
    "Hypno" to listOf("BUG", "GHOST"),
    "Krabby" to listOf("ELECTRIC", "GRASS"),
    "Kingler" to listOf("ELECTRIC", "GRASS"),
    "Voltorb" to listOf("GROUND"),
    "Electrode" to listOf("GROUND"),
    "Exeggcute" to listOf("FIRE", "ICE", "FLYING", "POISON"),
    "Exeggutor" to listOf("FIRE", "ICE", "FLYING", "POISON"),
    "Cubone" to listOf("WATER", "GRASS", "ICE"),
    "Marowak" to listOf("WATER", "GRASS", "ICE"),
    "Hitmonlee" to listOf("PSYCHIC", "FLYING"),
    "Hitmonchan" to listOf("PSYCHIC", "FLYING"),
    "Lickitung" to listOf("FIGHTING"),
    "Koffing" to listOf("GROUND", "PSYCHIC"),
    "Weezing" to listOf("GROUND", "PSYCHIC"),
    "Rhyhorn" to listOf("WATER", "GRASS", "ICE", "STEEL"),
    "Rhydon" to listOf("WATER", "GRASS", "ICE", "STEEL"),
    "Chansey" to listOf("FIGHTING"),
    "Tangela" to listOf("FIRE", "ICE", "FLYING", "POISON"),
    "Kangaskhan" to listOf("FIGHTING"),
    "Horsea" to listOf("ELECTRIC", "GRASS"),
    "Seadra" to listOf("ELECTRIC", "GRASS"),
    "Goldeen" to listOf("ELECTRIC", "GRASS"),
    "Seaking" to listOf("ELECTRIC", "GRASS"),
    "Staryu" to listOf("ELECTRIC", "GRASS"),
    "Starmie" to listOf("ELECTRIC", "GRASS"),
    "Mr. Mime" to listOf("STEEL", "POISON", "FIGHTING"),
    "Scyther" to listOf("FIRE", "ELECTRIC", "ROCK", "ICE"),
    "Jynx" to listOf("STEEL", "FIRE", "BUG", "ROCK"),
    "Electabuzz" to listOf("GROUND"),
    "Magmar" to listOf("WATER", "ROCK", "GROUND"),
    "Pinsir" to listOf("FIRE", "FLYING", "ROCK"),
    "Tauros" to listOf("FIGHTING"),
    "Magikarp" to listOf("ELECTRIC"),
    "Gyarados" to listOf("ELECTRIC", "ROCK"),
    "Lapras" to listOf("ELECTRIC", "FIGHTING", "ROCK"),
    "Ditto" to listOf("FIGHTING"),
    "Eevee" to listOf("FIGHTING"),
    "Vaporeon" to listOf("ELECTRIC", "GRASS"),
    "Jolteon" to listOf("GROUND"),
    "Flareon" to listOf("WATER", "ROCK", "GROUND"),
    "Porygon" to listOf("FIGHTING"),
    "Omanyte" to listOf("ELECTRIC", "GRASS", "STEEL"),
    "Omastar" to listOf("ELECTRIC", "GRASS", "STEEL"),
    "Kabuto" to listOf("ELECTRIC", "GRASS", "STEEL"),
    "Kabutops" to listOf("ELECTRIC", "GRASS", "STEEL"),
    "Aerodactyl" to listOf("ELECTRIC", "ICE", "ROCK"),
    "Snorlax" to listOf("FIGHTING"),
    "Articuno" to listOf("FIRE", "ROCK", "ELECTRIC"),
    "Zapdos" to listOf("ICE", "ROCK", "FIRE"),
    "Moltres" to listOf("WATER", "ROCK", "ELECTRIC"),
    "Dratini" to listOf("ICE", "DRAGON"),
    "Dragonair" to listOf("ICE", "DRAGON"),
    "Dragonite" to listOf("ICE", "DRAGON", "ROCK"),
    "Mewtwo" to listOf("BUG", "GHOST", "DARK"),
    "Mew" to listOf("BUG", "GHOST", "DARK")
)
